### ISSUE TITLE
v2 source files

### ISSUE THREAD

**Issue by TroniPM** [matheusmcardoso/ODK-DarkEmu#1]
hello, do you own the v2 source files server/client or do you know where i can to find it?

**Comment by cardoso** [comment]
I think i still have v2's client and server source in my old hard drive, but DarkEden community is dead and i have no time or motivation to release it right now (if the hard drive even works anymore).

**Comment by TroniPM** [comment]
Not everyone i guess... I hope you can reach and share these files so i can play around with them, and, if all be done successfully, create some nostalgic free 4fun server for the old ones :). []'s

**Comment by TroniPM** [comment]
@cardoso, news about it?

**Comment by RickKnockout** [comment]
Hey Cardoso, I'm also in search for the V2 sources... Really would love to read through them. I would be willing to compensate you for your time if need be. Great work on this DarkEmu by the way, it was very educational.

**Comment by TroniPM** [comment]
:(
